name: Bug
description: Something is broken
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: Bug summary
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected vs Actual behavior
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options: [Critical, High, Medium, Low]
    validations:
      required: true
